### ISSUE TITLE
Cannot run `vision6D` outside of the repo

### ISSUE THREAD

**Issue by edavalosanaya** [ykzzyk/vision6D#15]
If you run the `vision6D` entry point within the GitHub repo, it works. Outside, it does not.

This is the error: 

```bash
(ettk_dev) eduardo@avocado-XPS-13-9300:~/GitHub$ vision6D
Traceback (most recent call last):
  File "/home/eduardo/anaconda3/envs/ettk_dev/bin/vision6D", line 5, in <module>
    from vision6D.entry.main import main
  File "/home/eduardo/GitHub/vision6D/vision6D/entry/main.py", line 16, in <module>
    from .. import MyMainWindow
ImportError: cannot import name 'MyMainWindow' from 'vision6D' (unknown location)

```

**Comment by edavalosanaya** [comment]
Addressed by @ykzzyk
